services:
  - type: web
    name: bitespeed-identity-service
    env: node
    buildCommand: npm install
    startCommand: node src/database/migrate.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
